Countdown Timer/CountdownTimer.py
Countdown Timer/README.md

Signed-off-by: Justin T Joseph <jtjjust@gmail.com>

add CountdownTimer.py & README.md files in my directory

---

1st python program

Im unable to add my output there so i added here please accept it .

add 1st program

---

QR Generator/README.md
QR Generator/qr_generator.py

install pyrcode module into python using `pip install PyQRCode`
Then run qr_generator.py
Also added readme file explaining about the project.
Hope everything look fine. Kindly merge the PR with `hactoberfest-accepted` laber. Thanks :)
Happy hacktoberfest!

Implement QR generator using python

---

BMI.py

I have made a BMI calculator using python. I am a contributor at hacktoberfest2022. Please accept my PR under hacktoberfest

BMI calculator

---

Audio Book/Discord_bot_python.py

added discord bot python please check it and merge also give label as hactoberfest-accepted

added discord bot python

---

Color game/Readme.md
Color game/app.py

Enter the color of the text to win points
Enter the color of the words displayed below. And Keep in mind not to enter the word text itself and to move for next text press the enter button
summiting for hacktoberfest

color game

---

OOPs Library/README.md
OOPs Library/oops_library.py

Hey! @kishanrajput23  I have added my project. Please merge it.

Added OOPs Library Project

---

Python/lavishsheth.md

My program that opens a window with fields: username and password and a button to submit values. User can enter the details for username, password and click on Login button. Once the button is clicked, a function is called to validate the credentials. we get the username and password entered by the user, and print it to the console.

Add My Python Login Page

---

merge_pdf.py

Script to merge two pdfs using PyPDF4 module.

PDF Merger

---

Clock project/README.md
Clock project/clock.py

This is a small miniproject of clock for the Hacktoberfest-2022.

Create clock.py 

---

Youtube Downloader/README.md
Youtube Downloader/Youtube Downloader.py

It is a python program to download youtube video

Youtube downloader

---

Friends.py

#hacktoberfest #hacktoberfest-accepted #contribute #open-source #hacktoberfest2022

Initial Commit

---

Patterns Using Turtle/HelixPattern.py
Patterns Using Turtle/README.md

Signed-off-by: Justin T Joseph <jtjjust@gmail.com>

Added Patterns using Turtle library

---

Calculator/Calculator.py
Calculator/ReadMe.md

I have added a folder named calculator
In the folder i have added my calculator code file 
I have also added a ReadMe file.
#3

Calculator by Python #3

---

Snake_Game/game.py

A snake game with graphics created using python, turtle, time, and random module. Please kindly check and merge the pull request.

Snake_game

---

Calculator-project/calculator.py

Calculator project using python and os module.

Add calculator project

---

Guessing-Game/README.md
Guessing-Game/main.py

Hey, I have added a Guessing Game in python !
Could you please merge the pr with the hacktoberfest accepted label.
Thanks.

Guessing game created

---

Game/README.md
Game/game.py

Please review my pr and merge in main branch .
by @adi-ray

Added advanced Rock, paper, scissor game in python

---

Create _Acronyms_using_Python.md

Create Acronyms using Python

---

url-web-scraper/ReadMe.md
url-web-scraper/url-web-scraper.py

Implemented URL web scraper in python using beautiful soup.

Url web scraper in python

---

Bulk File Rename/renameFiles.py

- os
**Before the script**
**After the script**

Bulk File Renamer

---

Destroyer-Tank/README.md
Destroyer-Tank/start.py

Battle between two tanks
Destroyer Tank is a single-player game where the player must dominate the enemy tank in order to win.
https://user-images.githubusercontent.com/49890655/193413617-c87859db-6bcf-496a-92c9-b1ac09fbbbbd.mp4
submitting for hacktoberfest

tank game added

---

IronMan_Jarvis_AI_Voice_Assistant.py/Jarvis.py
IronMan_Jarvis_AI_Voice_Assistant.py/Readme.md

Hey! I have added my project. Please merge it in your repository.

Added Project:  Iron Man Jarvis AI Desktop Voice Assistant 

---

Game/FlappyBird.py

Added Flappy Bird Program

---

Caesar cipher/README.md
Caesar cipher/cipher.py

Hey, I have added a Caesar cipher in python !
Could you please merge the pr with the hacktoberfest accepted label.
Thanks.

Caesar cipher created

---

guess-the-number.py

guess-the-number-game using python

Added Guess-the-number game

---

Steganography

Steganography

---

Convert-Fahrenheit-to-Celsius/Fahrenheit-to-Celsius.py
Convert-Fahrenheit-to-Celsius/README.md

Temperature converter

---

Encrypt files and folder/encrypt.py
Encrypt files and folder/requirements.txt

encryption script using python added.
Thanks for reading my pull request.

File and Folder encryption script added.

---

Pharmacy Management System Project In Python.py

hi, there this is my fourth PR in hachtoberfest2022 in this fest I created Pharmacy Management System Project In Python using Tkinter.

Pharmacy Management System Project In Python.py

---

mail-slicer/README.md
mail-slicer/slicer.py

An Email slicer is a very useful program for separating the username and domain name of an email address. In this article, I will explain how to write a program to create an Email Slicer with Python.

Mail-slicer

---

Show_Github_Followers.py

updates github followers using python and shows on readme

---

TEXTtoHANDWRITTEN.py

text to handwitten notes program

---

Live_Weather_Desktop_Notifications/Readme.md
Live_Weather_Desktop_Notifications/weather.py

Hey! I have added  Live weather Desktop Notification. Please merge it into your repository.

Added Live Weather Desktop Notification

---

Lottery/Lottery.py
Lottery/Readme.md

Lottery Game

---

Best_game.py

please add my file in your repository with label hacktoberfest.

hacktoberfest-2022

---

java_inheritance_code/vss240.md

added my code of inheritance

---

Contact_Book_Management/Info.txt

I have made contact book management system using Python.

Contact book management

---

simplePythonScripts/baseVar.py
simplePythonScripts/conditionif.py
simplePythonScripts/convertToJSON.py
simplePythonScripts/demo2.py
simplePythonScripts/demoPrime.py
simplePythonScripts/func.py
simplePythonScripts/greet.py
simplePythonScripts/if_statement.py
simplePythonScripts/intervalPrimeNumber.py
simplePythonScripts/iterator.py
simplePythonScripts/lambda.py
simplePythonScripts/list.py
simplePythonScripts/script0.py
simplePythonScripts/tuple.py

The intention of this folder is to help any beginner with simple python commands - commands that help solve other challenges.

Simple Python Scripts

---

Credit-card-validator.py

Hi, there this is my third PR in Hacktoberfest2022 in this is have created my project named Credit-card-validator in python.

Credit-card-validator.py

---

text_cleaner/README.md
text_cleaner/remove_punctuation_numbers.py

Adding a project with a Python script that cleans an input text, removing punctuation and numbers.

Add text cleaner project

---

Convert-Fahrenheit-to-Celsius/Fahrenheit-to-Celsius.py
Convert-Fahrenheit-to-Celsius/README.md
Temperature Conversions/README.md
Temperature Conversions/main.py
calculator/README.md

Signed-off-by: SRIHARI S <sshsrn@gmail.com>

Added all Temperature unit conversions

---

BankProfit/BankProfitcal.py

Added Python Code To calculate Max Profit

Added Bankprofit python code

---

AgeCalculator.py

I am a contributor at hacktoberfest 2022. I have made a age calculator app using python. It will opens up a interface from where we can calculate our age. Please accept my PR if possible and also add label hacktoberfest accepted and all others.
Thank you

Age Calculator App

---

insta_reels_downloader_pro/Readme.md
insta_reels_downloader_pro/instaReels/reels.py

I have created a Instagram reels downloader pro with python using Tkinter, instascrape

Insta reels downloader pro

---

HappyNumber/HappyNo.py

Loop Condition Detecter

---

Merging list without duplicates/README.md
Merging list without duplicates/merging.py

Merging without duplicates

---

pdf viewer.py

Hey, I added a PDF viewer python project.
please have a look and accept the PR

added pdf viewer

---

SpotifyPlaylistGenerator/README.md
SpotifyPlaylistGenerator/main.py

playlist generator using python

added a spotify playlist generator

---

Mobile no module/README.md
Mobile no module/mobile_no_module.py

Mini project on Mobile no Module using python for Hacktoberfest 2022.

Create mobile no module

---

login-page/README.md
login-page/login_page.py
login-page/maharshi.sinha

Add this project under `Hacktoberfest 2022`

Login Page Using `Python`

---

Bounce Ball Game/game.pyw

Signed-off-by: gsaksham108 <gsaksham108@gmail.com>
**Hello Sir,**
I have created a GUI based **Bounce Ball Game** in Python using Tkinter library.
I request you to please review and merge the python program.

Bounce Ball Game

---

Credit-card-identifier.py

Hi, there this is my Second PR in Hacktoberfest2022 in this is have created my project named Credit-card-indentifier in python.

Credit-card-identifier.py

---

Pharmacy Management System Project.py

hi, there this is my fourth PR in hachtoberfest2022 in this fest I created Pharmacy Management System Project In Python using Tkinter.

Pharmacy Management System Project.py

---

basicquizgame.py/Noor44555.md

In this python program i basically created a small quiz game in which you can write the answer and check whether its correct or not.

Added a Basic Quiz Game

---

Text Based Adventure Game.py
TextToSpeech.py

This is a RPG (Role Playing Game) Text-Based game .  Where you are going to Trap as a warrior in jungle you have to pass hurdle to achieve points. i have also added guiding text in game for better understanding of controls..
Feel free to make changes in project.
please accept this project under Hacktoberfest2022!

Adding python game

---

OTP-Verification-System/OtpVerification.py
OTP-Verification-System/readme.md

OTP Verification is the process of verifying a user by sending a unique password so that the user can be verified before completing a registration or payment process. Most of the time, we get an OTP when we make an online payment, when we forget our password, or when creating an account on any online platform. Thus, the sole purpose of an OTP is to verify the identity of a user by sending a unique password.

OTP verification Using Python

---

scrapping_timesjobs_website.py

scrapping timesjobs.com for python skill

scrapping timesjobs.com

---

PasswordGenerator

It is password generator program in which the combination of letters digits and symbols of length 8 is generated.

Password Generator

---

RockPaperScissors

In this project we created a simple game by using Python in which we give inputs and this is a total of 3 Rounds after 3 Rounds we get a winner either it is user or the computer.

Rock Paper Scissors

---

madlib/Guess/gess_number.py

Hey, I've added python code for guess the number game in which a player can play with computer. Please accept my PR.

guess the number game

---

WiFi Password Knower/wifi.py

It will list (tell) your all the password(s) of your surrounding WiFi's.

WiFi Password Knower!

---

Use Phone camera with python/project.py

Use phone camera with python

---

KadaneAlgorithm.py

Kadane’s Algorithm is an iterative [dynamic programming]algorithm. It calculates the maximum sum subarray ending at a particular position by using the maximum sum subarray ending at the previous position.

Added Kadanes algorithm

---

Python Random Color Matrix Genertor

File Proposal: Random Grid Creator
Introduction:
The purpose of this file is to create a randomized grid using the Pygame library in Python. The grid is created by specifying the number of rows and columns and assigning random colors to each grid square. The user can adjust the size of the grid by changing the number of rows and columns.
Functionality:
The file will generate a randomized grid of squares using Pygame. Each square will have a random color assigned to it, and the size of the grid can be adjusted by changing the number of rows and columns. The user will be prompted to input the number of rows and columns they desire. If the input is not an integer, an error message will be displayed.
The file will use the Object class to create each grid square, which inherits from the Pygame …

A Dynamic Grid Generator

---

WebButton_SimpelGUI/README.md
WebButton_SimpelGUI/WebButtonSimpelGUI.py

Added new project
This project is a simple GUI application built using Python and the Tkinter library. The project demonstrates how to create a basic(straight simple) GUI application using Tkinter and how to handle button clicks to perform specific actions such as opening web pages. The icons for the buttons can be customized by providing the respective image paths or URLs.

Adding a new project(WebButtonSimpelGUI)

---

Morse Code/encrypter-decrypter.py

changed condition into one line

Inline condition in encrypted fn

---

Animal-Quiz-Game/quizz.py

Updated quizz.py

---

Currency-Converter/Converter-Converter.py
Currency-Converter/readme.md

I have added a new Python project- Currency Converter. 
I have also created the corresponding readme file explaining what it does.
Kindly consider merging this request for Hacktoberfest 2023. Thank you!

Added New Project - Currency Converter 

---

"Python PDF Sorter"

"Python PDF Sorter is a GUI application that allows you to organize and sort PDF files based on keywords, minimum file size, and specified page ranges. Simply input your preferences, select a folder containing PDFs, and let the program automatically categorize and move the files accordingly."

Create "Python PDF Sorter"

---

Typing_Game/typing.py

Closes issue #316 
I have created the Python Typing Game as per the specifications mentioned in the issue #316. The game is functional, allowing users to practice and improve their typing skills. It is built using Python and provides an interactive typing experience.

feat: Create a Python Typing Game
